graph LR
  numbers --> sets --> set_operations --> set_notations
  numbers --> number_operations --> algebra
  numbers --> fractions 
  numbers --> surds
  numbers --> equations
  numbers --> proportionality
  algebra --> functions --> classifying_functions --> one_to_one
  classifying_functions --> onto
  classifying_functions --> monotonic_functions 
  functions --> transforming --> inverse_functions --> hyperbolic_functions --> exponential_logarithmic
  functions --> composite_functions
  functions --> linear_functions
  functions --> quadratic_functions --> polynomials
  functions --> function_graphs --> trig_graphs
  numbers --> angles --> periodicity --> unit_circle --> trig_relationships --> trig_graphs --> inverse_trig_functions
  trig_relationships --> trig_equations --> tangent
  functions --> tangent
  trig_equations --> trig_formula --> sinusoidal_models
  limits --> continuity
  polynomials --> differentiation --> tangent --> increasing_decreasing
  functions --> increasing_decreasing
  differentiation --> derivative_rules --> second_derivative --> minima_maxima --> curve_sketching
  derivative_rules --> chain_rule
  composite_functions --> chain_rule
  second_derivative --> applications_of
  polynomials --> exponentials
  curve_sketching --> exponentials
  polynomials --> logarithms
  curve_sketching --> logarithms
  functions --> sequences --> series --> limits
  second_derivative --> integration --> by_subst --> definite_integral --> areas --> applications_of_di
  integration --> by_parts --> definite_integral
  definite_integral --> estimates_of_di
  intervals
  vectors --> position_displacement
  vectors --> vector_operations --> dot_product --> vector_angles --> orthogonal_projection
  vectors --> matrices --> matrix_operations --> matrix_multiplication 
  matrices --> linear_systems --> row_operations --> homogenous_equations
  vector_operations --> determinants --> cross_product --> areas_triple
  linear_systems --> equations_lines --> 2D --> 3D --> equations_planes --> intersections
  differentiation --> ode --> separable_equations
  functions --> ode
  sets --> intervals
  numbers --> vectors
  trig_equations --> trig_functions
  second_derivative --> monotonic_functions
  numbers --> data_classification
  function_graphs --> graphs_of_data
  variables --> association
  variables --> categorical
  sets --> lists --> summaries
  lists --> bucketing --> histograms
  axis --> labelling --> histograms
  associations --> axis
  labelling --> boxplots
  labelling --> scatterplots
  variables --> random_vars
  probability --> random_vars --> mean_variance --> binomial
  mean_variance --> discrete_continuous
  mean_variance --> normal
  lists --> data_frame --> pivot
  lists --> populations --> probability
  probability --> distributions --> areas_under
  integration --> areas_under
  distributions --> sampling_distros --> sample_means
  sampling_distros --> standard_error
  sample_means --> confidence_intervals --> z-test
  confidence_intervals --> t_test --> anova
  sampling_distros --> dof
